name: Build-QuyHoang-Dylib
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: theos/setup-theos@v1
      - name: Build Dylib
        run: make package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuyHoang-Elite-Dylib
          path: .theos/obj/debug/*.dylib
